import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const lock = JSON.parse(fs.readFileSync(path.join(root, 'sdk/package-lock-info.json'), 'utf8'));
const cache = path.join(root, '.build/sdk');
fs.mkdirSync(cache, { recursive: true });
const result = JSON.parse(execFileSync('npm', ['pack', `${lock.name}@${lock.version}`, '--json', '--ignore-scripts', '--pack-destination', cache], { encoding: 'utf8' }))[0];
const tarball = path.join(cache, result.filename);
const integrity = 'sha512-' + createHash('sha512').update(fs.readFileSync(tarball)).digest('base64');
if (integrity !== lock.integrity) throw new Error('SDK integrity does not match retained artifact');
execFileSync('tar', ['-xzf', tarball, '-C', cache]);
const pkg = JSON.parse(fs.readFileSync(path.join(cache, 'package/package.json'), 'utf8'));
const exported = pkg.exports['./client/host-bridge'];
if (exported !== './dist/client/host-bridge.js') throw new Error('SDK export changed');
const source = fs.readFileSync(path.join(cache, 'package', exported), 'utf8');
if (/^import\s/m.test(source)) throw new Error('Portable export acquired runtime dependencies; review needed');
console.log(JSON.stringify({ package: result.id, integrityVerified: true, exported, browserBytes: Buffer.byteLength(source) }));
